version: '3.0'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - 8086:5000
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    volumes:
      - .:/app
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example